# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: quantbench api

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /markets:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Market` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
       - $ref: "#/parameters/pageSize"
       - $ref: "#/parameters/pageNumber"
       
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfMarkets
            type: array
            items:
              $ref: '#/definitions/Market'

definitions:
  Market: 
    type: object
    properties:
      name:
        type: string
        description: Name of the market.
      open_time:
        type: integer
        format: int32
        description: Open time of the market.
      close_time:
        type: integer
        format: int32
        description: Close time of the market.
parameters:
  pageSize:
    name: pageSize
    in: query
    description: Number of items to return per page.
    type: integer
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
    